// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCU4x9lXpe6u_QsO5cTyJHUGxk5Mq2b3I',
    appId: '1:355494541447:web:36ec47166881c24b6d6022',
    messagingSenderId: '355494541447',
    projectId: 'astros-45a3f',
    authDomain: 'astros-45a3f.firebaseapp.com',
    databaseURL: 'https://astros-45a3f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'astros-45a3f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF87kXMyTxwhHo1BCcdPC0nhpxYkHkAzg',
    appId: '1:355494541447:android:9692877fb39893696d6022',
    messagingSenderId: '355494541447',
    projectId: 'astros-45a3f',
    databaseURL: 'https://astros-45a3f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'astros-45a3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1I1aykb6fCRkqj1p8suEuw2-gXqnpsh8',
    appId: '1:355494541447:ios:de248368ab300a726d6022',
    messagingSenderId: '355494541447',
    projectId: 'astros-45a3f',
    databaseURL: 'https://astros-45a3f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'astros-45a3f.firebasestorage.app',
    iosBundleId: 'com.example.newastros',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1I1aykb6fCRkqj1p8suEuw2-gXqnpsh8',
    appId: '1:355494541447:ios:de248368ab300a726d6022',
    messagingSenderId: '355494541447',
    projectId: 'astros-45a3f',
    databaseURL: 'https://astros-45a3f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'astros-45a3f.firebasestorage.app',
    iosBundleId: 'com.example.newastros',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCU4x9lXpe6u_QsO5cTyJHUGxk5Mq2b3I',
    appId: '1:355494541447:web:1efa113cb3eb1c186d6022',
    messagingSenderId: '355494541447',
    projectId: 'astros-45a3f',
    authDomain: 'astros-45a3f.firebaseapp.com',
    databaseURL: 'https://astros-45a3f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'astros-45a3f.firebasestorage.app',
  );
}
